version: 2
project_name: opslevel-runner
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
dockers:
  - image_templates:
    - "public.ecr.aws/opslevel/opslevel-runner:latest"
    - "public.ecr.aws/opslevel/opslevel-runner:{{ .Tag }}"
    build_flag_templates:
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Tag }}"
brews:
  - name: opslevel-runner
    homepage: "https://www.opslevel.com/"
    description: "Command line tool that runs jobs for OpsLevel"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "opslevel-runner"
    test: |
      system "#{bin}/opslevel-runner version"
    repository:
      owner: opslevel
      name: homebrew-tap
      token: "{{ .Env.ORG_GITHUB_TOKEN }}"
checksum:
  name_template: '{{ .ProjectName }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  sort: desc
  filters:
    exclude:
      - "^Merge"
release:
  prerelease: auto
