name: "Reports"

# Every Monday at 1PM UTC (9AM EST)
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 13 * * 1"

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Report Coverage To OpsLevel
        run: |-
          export DATA=$(curl -s -X GET -H "Authorization: ${CODECOV_TOKEN}" https://codecov.io/api/gh/${GITHUB_REPOSITORY}/branch/main)
          echo ${DATA} | curl -s -X POST ${{ secrets.OL_COVERAGE_INTEGRATION_URL }} -H 'content-type: application/json' -d @-
